[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.module]
source = "compat/init.lua"
before = "main.lua"
name = "typist.compat.init"

[[patches]]
[patches.module]
source = "compat/fhotkey.lua"
before = "main.lua"
name = "typist.compat.fhotkey"
